
TYPE
	HA_TypeSelect_typ : 	STRUCT 
		Select : HA_TYPE_ENUM;
		VarSINT : SINT;
		VarUSINT : USINT;
		VarINT : INT;
		VarUINT : UINT;
		VarDINT : DINT;
		VarUDINT : UDINT;
		VarREAL : REAL;
		VarLREAL : LREAL;
		VarTIME : TIME;
		VarDT : DATE_AND_TIME;
		VarSTRING_ADR : UDINT;
		VarSTRING_LEN : UDINT;
		VarWSTRING_ADR : UDINT;
		VarWSTRING_LEN : UDINT;
	END_STRUCT;
	HA_TYPE_ENUM : 
		(
		HA_TYPE_INT,
		HA_TYPE_USINT,
		HA_TYPE_SINT,
		HA_TYPE_UINT,
		HA_TYPE_DINT,
		HA_TYPE_UDINT,
		HA_TYPE_REAL,
		HA_TYPE_LREAL,
		HA_TYPE_TIME,
		HA_TYPE_DT,
		HA_TYPE_STRING,
		HA_TYPE_WSTRING
		);
END_TYPE
